---
- name: Setup Development Environment
  hosts: all

  vars_files:
    - vars/homebrew.yml
    - vars/rubygems.yml
    - vars/masapps.yml
    - vars/dockapps.yml

  pre_tasks:
    - include_vars: vars/dotfiles-{{ ansible_os_family }}.yml

    - include_tasks: tasks/linux.yml
      when: ansible_os_family == "Debian"
      tags:
      - packages

    - include_tasks: tasks/zsh.yml
      tags:
      - zsh

    - include_tasks: tasks/ruby.yml
      tags:
      - ruby

  post_tasks:
    # Linux stuff
    - include_tasks: tasks/node-linux.yml
      when: ansible_os_family == "Debian"
      tags:
      - node

    # Mac stuff
    - include_tasks: tasks/react-native.yml
      when: ansible_os_family == "Darwin"
      tags:
      - react-native

  roles:
    - role: sicruse.powerline-fonts
      tags:
      - powerline

    - role: geerlingguy.dotfiles
      tags:
      - dotfiles

    - role: geerlingguy.homebrew
      when: ansible_os_family == "Darwin"
      tags:
      - homebrew

    - role: geerlingguy.mas
      when: ansible_os_family == "Darwin"
      tags:
      - mas

    - role: sicruse.dockapps
      when: ansible_os_family == "Darwin"
      tags:
      - dockapps
