---
- name: Setup MacOSX Development Environment
  hosts: all
  vars:
    rbenv:
      ruby_version: 2.3.1

  tasks:
    - name: Install foundational opensource tools
      homebrew:
        name: '{{ item.name | default(item) }}'
        state: '{{ item.state | default("present") }}'
      with_items:
        - git
        - rbenv

    - name: Install foundational Apps
      homebrew_cask:
        name: '{{ item.name | default(item) }}'
        state: '{{ item.state | default("present") }}'
      with_items:
        - google-chrome
        - sourcetree

    - name: check ruby {{ rbenv.ruby_version }} installed for system
      shell: $SHELL -lc "rbenv versions | grep {{ rbenv.ruby_version }}"
      register: ruby_installed
      changed_when: false
      ignore_errors: yes
      always_run: yes
      tags:
        - rbenv

    - name: install ruby {{ rbenv.ruby_version }} for system
      shell: bash -lc "rbenv install {{ rbenv.ruby_version }}"
      when:
        - ruby_installed.rc != 0

    - name: Install foundational ruby gems
      gem:
        name: '{{ item.name | default(item) }}'
        state: '{{ item.state | default("present") }}'
      with_items:
        - cocoapods
        - fastlane
