---
- name: Setup Development Environment
  hosts: all

  vars_files:
    - vars/vars.yml
    - vars/powerline-fonts.yml
    - vars/ruby-gems.yml
    - vars/dock-apps.yml
    - vars/dock-folders.yml

  pre_tasks:
    - include_tasks: tasks/git.yml
    - include_tasks: tasks/ruby.yml
    - include_tasks: tasks/oh-my-zsh.yml

  post_tasks:
    # Linux stuff
    - include_tasks: tasks/node.yml
      when: ansible_os_family == "Debian"
    - include_tasks: tasks/watchman.yml
      when: ansible_os_family == "Debian"
    # Mac stuff
    - include_tasks: tasks/flyway.yml
      when: ansible_os_family == "Darwin"
    - include_tasks: tasks/iterm.yml
      when: ansible_os_family == "Darwin"
    - include_tasks: tasks/react-native.yml
      when: ansible_os_family == "Darwin"

  roles:
    - sicruse.powerline-fonts
    - { role: sicruse.dockapps, when: ansible_os_family == 'Darwin' }
