---
- name: Setup Development Environment
  hosts: all

  vars_files:
    - vars/homebrew.yml
    - vars/rubygems.yml
    - vars/masapps.yml
    - vars/dockapps.yml
    - "vars/dotfiles-{{ ansible_os_family|lower }}.yml"

  pre_tasks:
    # Linux
    - name: Install linux packages
      import_tasks: tasks/linux.yml
      when: ansible_os_family == "Debian"
      tags:
      - packages

    # Universal
    - name: Install zsh
      import_tasks: tasks/zsh.yml
      tags:
      - zsh
    - name: Install ruby
      import_tasks: tasks/ruby.yml
      tags:
      - ruby

  post_tasks:
    # Linux
    - name: Install node for linux
      import_tasks: tasks/node-linux.yml
      when: ansible_os_family == "Debian"
      tags:
      - node

    # Mac
    - name: Install react native
      import_tasks: tasks/react-native.yml
      when: ansible_os_family == "Darwin"
      tags:
      - react-native

  roles:
    # Universal roles
    - { role: sicruse.powerline-fonts,  tags: ['powerline'] }
    - { role: geerlingguy.dotfiles,     tags: ['dotfiles'] }
    # Mac roles
    - { role: geerlingguy.homebrew,     tags: ['homebrew'], when: ansible_os_family == "Darwin" }
    - { role: geerlingguy.mas,          tags: ['mas']     , when: ansible_os_family == "Darwin" }
    - { role: sicruse.dockapps,         tags: ['dockapps'], when: ansible_os_family == "Darwin" }
