---
- name: Setup MacOSX Development Environment
  hosts: all

  vars_files:
    - vars/vars.yml
    - vars/ruby_gems.yml
    - vars/dock-apps.yml
    - vars/dock-folders.yml 

  pre_tasks:
    - include: tasks/git.yml
    - include: tasks/ruby.yml
    - include: tasks/oh-my-zsh.yml
    - include: tasks/powerline-shell.yml
    - include: tasks/iterm.yml
    - include: tasks/flyway.yml
    - include: tasks/react-native.yml

  roles:
    - sicruse.dockapps