---
- name: Setup MacOSX Development Environment
  hosts: all
  vars:
    rbenv:
      ruby_version: 2.3.1

  tasks:
    - name: Install foundational opensource tools
      homebrew:
        name: '{{ item.name | default(item) }}'
        state: '{{ item.state | default("present") }}'
      with_items:
        - git
        - rbenv

    - name: Install foundational Apps
      homebrew_cask:
        name: '{{ item.name | default(item) }}'
        state: '{{ item.state | default("present") }}'
      with_items:
        - google-chrome
        - sourcetree

    - name: update .bash_profile to include rbenv
      become: yes
      become_user: sicruse
      lineinfile: dest=~/.profile regexp='' insertafter=EOF line='eval "$(rbenv init -)"' state=present create=True

    - name: check ruby {{ rbenv.ruby_version }} installed for system
      shell: $SHELL -lc "rbenv versions | grep {{ rbenv.ruby_version }}"
      register: ruby_installed
      changed_when: false
      ignore_errors: yes
      always_run: yes
      tags:
        - rbenv

    - name: install ruby {{ rbenv.ruby_version }}
      shell: bash -lc "rbenv install {{ rbenv.ruby_version }}"
      when:
        - ruby_installed.rc != 0
      tags:
        - rbenv
        
    - name: check if current system ruby version is {{ rbenv.ruby_version }}
      shell: $SHELL -lc "rbenv version | cut -d ' ' -f 1 | grep -Fx '{{ rbenv.ruby_version }}'"
      register: ruby_selected
      changed_when: false
      ignore_errors: yes
      always_run: yes
      tags:
        - rbenv

    - name: set ruby {{ rbenv.ruby_version }} for system
      shell: bash -lc "rbenv global {{ rbenv.ruby_version }} && rbenv rehash"
      when:
        - ruby_selected.rc != 0
      tags:
        - rbenv

    - name: Install foundational ruby gems
      become: yes
      become_user: sicruse
      gem:
        name: '{{ item.name | default(item) }}'
        state: '{{ item.state | default("present") }}'
      with_items:
        - cocoapods
        - fastlane
