---
- name: Setup MacOSX Development Environment
  hosts: all

  tasks:
    - name: Install foundational opensource tools
      homebrew:
        name: '{{ item.name | default(item) }}'
        state: '{{ item.state | default("present") }}'
      with_items:
        - git
        
    - name: Install foundational Apps
      homebrew_cask:
        name: '{{ item.name | default(item) }}'
        state: '{{ item.state | default("present") }}'
      with_items:
        - google-chrome
        
    - name: Install foundational ruby gems
      gem:
        name: '{{ item.name | default(item) }}'
        state: '{{ item.state | default("present") }}'
      with_items:
        - cocoapods
        - fastlane
