---
# tasks file for foundational tools
  - name: Install git & git-flow
    apt:
      name: '{{ item.name | default(item) }}'
      state: '{{ item.state | default("present") }}'
    become: true
    with_items:
      - git
      - git-flow
