---
# tasks file for foundational tools
  - name: Install git & git-flow
    homebrew:
      name: '{{ item.name | default(item) }}'
      state: '{{ item.state | default("present") }}'
    with_items:
      - git
      - git-flow

  - name: Configuring git
    become: yes
    become_user: '{{ user_id }}'
    template: >
      src=gitconfig.j2
      dest=~/.gitconfig
      mode=0755        
