---
  - name: Install the gpg key for nodejs LTS
    become: true
    apt_key:
      url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
      state: present

  - name: Install the nodejs LTS repos
    become: true
    apt_repository:
      repo: "deb https://deb.nodesource.com/node_7.x {{ ansible_distribution_release }} main"
      state: present
      update_cache: yes

  - name: Install the nodejs
    become: true
    apt:
      name: nodejs
      state: present

  # - name: Install npm global packages
  #   become: true
  #   npm:
  #     name: '{{ item.name | default(item) }}'
  #     state: '{{ item.state | default("present") }}'
  #     version: '{{ item.version | default(omit) }}'
  #     production: '{{ item.production | default(omit) }}'
  #     global: True
  #   with_items:
  #     - nuclide

  - name: Check is watchman installed
    shell: command -v watchman >/dev/null 2>&1
    register: is_watchman_exist
    ignore_errors: yes

  - name: Install build tools & build watchman
    block:
      - package:
          name: '{{ item.name | default(item) }}'
          state: '{{ item.state | default("present") }}'
        become: true
        with_items:
          - libssl-dev
          - autoconf
          - automake
          - libtool

      - git:
          repo: https://github.com/facebook/watchman.git
          version: v4.9.0
          dest: /tmp/watchman
          accept_hostkey: yes

      - command: ./autogen.sh
        args:
          chdir: /tmp/watchman

      - command: ./configure
        args:
          chdir: /tmp/watchman

      - command: make
        args:
          chdir: /tmp/watchman

      - command: make install
        become: true
        args:
          chdir: /tmp/watchman

    when: is_watchman_exist == False
