---
# tasks file for powerline shell
  - name: Cloning powerline shell
    become: yes
    become_user: '{{ user_id }}'
    git:
      repo=https://github.com/sicruse/powerline-shell.git
      dest=~/.powerline-shell        

  - name: Writing new powerline-shell config
    become: yes
    become_user: '{{ user_id }}'
    template: >
      src=powerline-shell-config.py.j2
      dest=~/.powerline-shell/config.py
      mode=0755     

  - name: Configuring powerline-shell
    become: yes
    become_user: '{{ user_id }}'    
    shell: ./install.py
    args:
      chdir: ~/.powerline-shell
      creates: powerline-shell.py
    # ignore_errors: true

  - name: Creating powerline-shell symlink
    become: yes
    become_user: '{{ user_id }}'
    file: src=~/.powerline-shell/powerline-shell.py dest=~/.powerline-shell.py state=link

  - name: Cloning powerline fonts
    become: yes
    become_user: '{{ user_id }}'
    git:
      repo=https://github.com/powerline/fonts.git
      dest=~/.powerline-fonts

  - name: Configuring powerline fonts
    become: yes
    become_user: '{{ user_id }}'    
    shell: ./install.sh
    args:
      chdir: ~/.powerline-fonts
    # ignore_errors: true


