---
  - name: Check is watchman installed
    shell: command -v watchman >/dev/null 2>&1
    register: is_watchman_exist
    ignore_errors: yes


  - name: Install build tools & build watchman
    block:
      - package:
          name: '{{ item.name | default(item) }}'
          state: '{{ item.state | default("present") }}'
        become: true
        with_items:
          - libssl-dev
          - autoconf
          - automake
          - libtool

      - git:
          repo: https://github.com/facebook/watchman.git
          version: v4.9.0
          dest: /tmp/watchman
          accept_hostkey: yes

      - command: ./autogen.sh
        args:
          chdir: /tmp/watchman

      - command: ./configure
        args:
          chdir: /tmp/watchman

      - command: make
        args:
          chdir: /tmp/watchman

      - command: make install
        become: true
        args:
          chdir: /tmp/watchman

    when: is_watchman_exist == False
