---
  # tasks file for zsh
  - name: Cloning oh-my-zsh
    become: yes
    become_user: '{{ ansible_user_id }}'
    git:
      repo=https://github.com/robbyrussell/oh-my-zsh
      dest=~/.oh-my-zsh

  - name: Cloning powerlevel9k theme
    become: yes
    become_user: '{{ ansible_user_id }}'
    git:
      repo=https://github.com/bhilburn/powerlevel9k.git
      dest=~/.oh-my-zsh/custom/themes/powerlevel9k

  - name: Setting user shell to zsh
    become: yes
    become_user: root
    user: name='{{ ansible_user_id }}' shell=/usr/local/bin/zsh
    when: ansible_os_family == "Darwin"

  - name: Setting user shell to zsh
    become: yes
    become_user: root
    user: name='{{ ansible_user_id }}' shell=/usr/bin/zsh
    when: ansible_os_family == "Debian"
